name: Build & Release

on:
  push:
    branches:
      - main
      - beta
      - next

jobs:
  build_and_release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build:prod

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
